### ISSUE TITLE
This plugin don't work. 

### ISSUE THREAD

**Issue by Tocho2018** [magekey/module-stores-flags#1]
Manager Add code to the site but flags don't show .

i don't know what is the problem!!!!

**Comment by magekey** [comment]
I did a fix for production compilation, but not sure it was your issue.
Could you send more details about problem?
Also keep in mind that Store Flags module replace the default language template (Magento_Store::switch/languages.phtml). It could be a problem if you use a custom theme and some layouts was overwrited.

**Comment by Tocho2018** [comment]
sure check my laguage.switcher

my site is

www.elgronebrazuca.com

![flag here](https://user-images.githubusercontent.com/35183662/35770723-3c0d62a8-08ff-11e8-84a5-a93ce36d39d8.JPG)

**Comment by Tocho2018** [comment]
where is the blue circle will show up the flag

**Comment by magekey** [comment]
Store Flags module was implemented for default luma theme with LESS compilation. Your custom theme based on SASS. Please email me to nick@magekey.com. We could discuss your problem and find a solution.

**Comment by magekey** [comment]
I added a new release 2.1.2. Look at **Use compiled styles** section in module description. This should helps you.

**Comment by magekey** [comment]
Added new release 2.1.3. **Use Compiled styles** options moved to admin settings.
