### ISSUE TITLE
module canno't be activated rigth now if enabled crash

### ISSUE THREAD

**Issue by Tocho2018** [magekey/module-stores-flags#2]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Store\Block\Switcher\Interceptor::escapeHtmlAttr

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Store\Block\Switcher\Interceptor::escapeHtmlAttr
#0 /home/elgroneb/public_html/vendor/magekey/module-stores-flags/view/frontend/templates/switch/languages.phtml(11): Magento\Framework\DataObject->__call('escapeHtmlAttr', Array)
#1 /home/elgroneb/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/elgroneb/...')
#2 /home/elgroneb/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Store\Block\Switcher\Interceptor), '/home/elgroneb/...', Array)
#3 /home/elgroneb/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/elgroneb/...')
#4 /home/elgroneb/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#5 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#6 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('store_language')
#7 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('store_language')
#8 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('store_language')
#9 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.switcher...')
#10 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('header.switcher...')
#11 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('header.switcher...')
#12 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.rightblo...')
#13 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('header.rightblo...')
#14 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('header.rightblo...')
#15 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.panel.gr...')
#16 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('header.panel.gr...')
#17 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('header.panel.gr...')
#18 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.panel')
#19 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('header.panel')
#20 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('header.panel')
#21 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('rd.navbar')
#22 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('rd.navbar')
#23 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('rd.navbar')
#24 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('rd.navbar-wrap')
#25 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('rd.navbar-wrap')
#26 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('rd.navbar-wrap')
#27 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.containe...')
#28 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('header.containe...')
#29 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('header.containe...')
#30 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#31 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#32 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper')
#33 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper.ou...')
#34 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper.ou...')
#35 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout->renderElement('page.wrapper.ou...')
#36 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#37 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout->renderNonCachedElement('root')
#38 /home/elgroneb/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout->renderElement('root')
#39 /home/elgroneb/public_html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#40 /home/elgroneb/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#41 /home/elgroneb/public_html/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#42 /home/elgroneb/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#43 /home/elgroneb/public_html/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#44 /home/elgroneb/public_html/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#45 /home/elgroneb/public_html/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#46 /home/elgroneb/public_html/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#47 /home/elgroneb/public_html/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#48 /home/elgroneb/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#49 /home/elgroneb/public_html/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#50 /home/elgroneb/public_html/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#51 /home/elgroneb/public_html/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#52 /home/elgroneb/public_html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#53 /home/elgroneb/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#54 /home/elgroneb/public_html/index.php(43): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#55 {main}

**Comment by magekey** [comment]
Which Magento version you have installed?
The new method "escapeHtmlAttr" was implemented since 2.2.0 version. So module didn't work with version lower that 2.2.0. Added fix for 2.1.11. Released version 2.1.4.

**Comment by Tocho2018** [comment]
Thank you my template only works in magento 2.1.7 i will try update again. Very thank you

Enviado desde mi iPhone

El 4 feb. 2018, a la(s) 15:33, Nicholas Miller <notifications@github.com<mailto:notifications@github.com>> escribió:


Which Magento version you have installed?
The new method "escapeHtmlAttr" was implemented since 2.2.0 version. So module didn't work with version lower that 2.2.0. Added fix for 2.1.11. Released version 2.1.4.

**Comment by Tocho2018** [comment]
Released Versión 2.1.4 Works perfectly very great job . Thank you a lot :).
