### ISSUE TITLE
Package incompatible with PHP 7.1

### ISSUE THREAD

**Issue by oviliz** [magekey/module-stores-flags#3]
Hi, unfortunately, I'm not able to install the module on my PHP 7.1 install.

>  [InvalidArgumentException]                                                                                         
>   Package magekey/module-stores-flags at version  has a PHP requirement incompatible with your PHP version (7.1.21)

**Comment by magekey** [comment]
@oviliz Thank you for your research. I added a php version to composer, now it should works correct.

**Comment by esprit-dev** [comment]
Hi, can you add php 7.2.x ? as your module seems to work well on this version too. Thx a lot
